name: Marc Ames Photography
favicon: null
layout_spectrum: 0.8751
typography_spectrum: 0.72435
title: Marc Ames Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf9f7'
    - '#deb9b1'
    - '#ac8181'
    - '#774c4a'
    - '#000000'
  brandStrength: 1
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0
purpose: []
