name: Marc Ames Photography
favicon: null
layout_spectrum: 0.8751
typography_spectrum: 0.89679
title: Marc Ames Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#262422'
    - '#4e4d48'
    - '#63615d'
    - '#82817d'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
